resolver: lts-3.15
packages:
- .
- upstream/snap-app

extra-deps:
- HJScript-0.7.0
- download-curl-0.1.4
- named-formlet-0.2
- HJavaScript-0.4.7
- hsp-0.10.0
- Diff-0.1.3
flags: {}
extra-package-dbs: []
